### PR TITLE
Update GUI

### PR DESCRIPTION
**Pull request by OfficialChrisTucker**

### CODE REVIEW

**Comment by 14Codes** [comment]
Alright, Are team will check over it looks good so far.

**Review by 14Codes — APPROVED** [review]
Good To go man! Besides "/**
* Copyright (c) Slushi 2023
* This file has been claimed and legally copyrighted
* by Slushi (Brydina). DO not reporoduce this or
* in any case make people think this is yours.
*
* © Jordan Copyright Chipping
*/" 

we can discuss that later.

**Comment by 14Codes** [comment]
Thanks dude!

**Comment by OfficialChrisTucker** [comment]
no problen

**Pull request merged**
